name: Generate LoC Badge

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  loc-badge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures all branches are fetched

      - name: Make Code Badge
        uses: shadowmoose/GHA-LoC-Badge@1.0.0
        with:
          directory: ./
          badge: ./badge.svg
          patterns: '*.ts|*.tsx|*.js'
          ignore: 'node_modules|dist|build'

      - name: Commit Badge to badges branch
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          
          # Switch or create the badges branch
          if git show-ref --quiet refs/heads/badges; then
            git checkout badges
          else
            git checkout --orphan badges
          fi

          # Reset branch content
          git rm -rf . || true

          # Move badge.svg into the clean branch
          git checkout main -- badge.svg

          # Commit and push
          git add badge.svg
          git commit -m "Update LoC badge" || echo "No changes to commit"
          git push -f origin badges
