name: Generate LoC Badge

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  loc-badge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Make Code Badge
        uses: shadowmoose/GHA-LoC-Badge@1.0.0
        id: badge
        with:
          debug: true
          directory: ./
          badge: ./badge.svg
          patterns: '*.ts|*.tsx|*.js'
          ignore: 'node_modules|dist|build'

      - name: Upload Badge to badges branch
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git checkout --orphan badges
          git reset
          mv badge.svg ./badge.svg
          git add badge.svg
          git commit -m "Update LoC badge"
          git push -f origin badges
